language: php
php:
	- 5.5
	- 5.4
	- hhvm
env:
	- DB=mysql
before_script:
	- if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS ghostdb;" -uroot; fi
script: phpunit --configuration phpunit_$DB.xml --coverage-text
	